name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: rootpassword  # Mot de passe pour l'utilisateur root
          MYSQL_DATABASE: ma_base_de_donnees  # Nom de la base de données à créer
          MYSQL_USER: delta                  # Utilisateur spécifique
          MYSQL_PASSWORD: delta
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17 (for Spring Boot backend)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Node.js (for Angular frontend)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Give execute permission to mvnw
      working-directory: ./backend
      run: chmod +x mvnw

    - name: Install backend dependencies
      working-directory: ./backend
      run: ./mvnw clean install

      env:
        SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/ma_base_de_donnees
        SPRING_DATASOURCE_USERNAME: delta
        SPRING_DATASOURCE_PASSWORD: delta

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build Angular frontend
      working-directory: ./frontend
      run: npm run build --prod

    - name: Create Docker images for backend and frontend
      run: |
        docker build -t myproject-backend ./backend
        docker build -t myproject-frontend ./frontend

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images
      run: |
        docker tag myproject-backend:latest ${{ secrets.DOCKER_USERNAME }}/myproject-backend:latest
        docker tag myproject-frontend:latest ${{ secrets.DOCKER_USERNAME }}/myproject-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/myproject-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/myproject-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y sshpass

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
  

    - name: Deploy via SSH
      env:
        SSHPASS: ${{ secrets.SSH_PASS }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        sudo apt-get update
        sudo apt-get install -y docker-compose
        
        if [ "$(sudo docker info | grep 'Swarm' | awk '{print $2}')" = "inactive" ]; then
        sudo docker swarm init
        fi


        # Créer le réseau Docker s'il n'existe pas
        if ! sudo docker network ls | grep -q 'web'; then
          sudo docker network create --driver overlay web
        fi

        sudo usermod -aG docker ${{ secrets.SSH_USER }}
        cd /home
        sudo docker-compose pull
        sudo docker stack deploy -c docker-compose.yml myproject-stack
        EOF
